### ISSUE TITLE
part_of

### ISSUE THREAD

**Issue by tiagochst** [lgatto/rols#21]
In rols v2.0 branch, I could find functions for parents, ancestors, children, but not for part_of.
Please, is it possible to add it?

Example of [json](https://www.ebi.ac.uk/ols/beta/api/ontologies/bto/terms?iri=http://purl.obolibrary.org/obo/BTO_0000562) with part_of.

**Comment by lgatto** [comment]
I am appending this here, as I believe it might be related
```r
# return NULL, but I was expecting central nervous system
qry <- olsSearch(OlsSearch(q = "brain",ontology = "BTO", exact=T))
parents(as(qry, "Terms")[[1]])


# return BTO:0000000 as expected
qry <- olsSearch(OlsSearch(q = "animal",ontology = "BTO", exact=T))
parents(as(qry, "Terms")[[1]])
```
![rols-brain-partof](https://cloud.githubusercontent.com/assets/384198/13530187/0cbe9e3c-e218-11e5-8436-447f8a1e634b.png)

**Comment by lgatto** [comment]
May be this will answer your question:

```r
> qry <- olsSearch(OlsSearch(q = "brain",ontology = "BTO", exact=T))
> trm <- as(qry, "Terms")[[1]]
> properties(trm)
Object of class 'Properties' with 2 entries
 From the BTO ontology
central nervous system, head 
```

Properties are not documented in the vignette yet, but see `class?Propoerties`.

**Comment by tiagochst** [comment]
I was able to solve my proble using this commit
<https://github.com/BioinformaticsFMRP/rols/commit/f278d912512f9411912d5adc721b0b5f5bfbc553>


> qry <- olsSearch(OlsSearch(q = "brain",ontology = "BTO", exact=T))> trm <- as(qry, "Terms")[[1]]> parents(trm)Object of class 'Terms' with 0 entries
 From the  ontologies
NULL > part_of(trm)Object of class 'Terms' with 2 entries
 From the BTO ontology
BTO:0000227, BTO:0000282



the properties(trm) as you showed also gave both BTO_0000227 and BTO_0000282

**Comment by lgatto** [comment]
> I was able to solve my proble using this commit <https://github.com/BioinformaticsFMRP/rols/commit/f278d912512f9411912d5adc721b0b5f5bfbc553>

That's great - would you mind sending a pull request to `master` for inclusion in rols?
