### ISSUE TITLE
Current building issue

### ISSUE THREAD

**Issue by lgatto** [lgatto/rols#24]
The vignette currently fails at `(qtrms <- as(qry, "Terms"))` (line `226`). This is because one of the results unexpectedly is missing its `obo_id`. This has been reported [here](https://github.com/EBISPOT/OLS/issues/153).

**Comment by lgatto** [comment]
See 40998e4ae8f08850277cda2ccce4499f7c80570e for details.

**Comment by aiyer-commits** [comment]
Hi @lgatto , I am receiving a subscript out of bounds issue (Error in x[["ontology_prefix"]]) when trying to create terms from a query of the Cell Ontology.

Is this the same issue as above?

I am using rols 2.10.1

**Comment by aiyer-commits** [comment]
Actually I had forgotten to do the olssearch conversion step as described in the vignette, however I am now getting a different error:  "error in .term(object, id, ...) : Not Found (HTTP 404)" 

This error does not occur when making a data.frame

**Comment by lgatto** [comment]
404 error points to a (probably temporary) network. I just checked and all seems fine on my side.
