### ISSUE TITLE
Pagination of ebi.ac.uk results

### ISSUE THREAD

**Issue by AndrewC160** [lgatto/rols#27]
Hello, apologies if this is outside of GitHub protocol (I'm somewhat new) or if I've missed something about how this function operates, but I've been helping a colleague use your package (it's excellent btw) and I ran into an issue with the descendants() function. While it does request as many pages from ebi.ac.uk as are required for a query, the website appears to still paginate the results in groups of 1,000. As such, the URL ending in "?page=0&size=1236" only contains result pages 0 through 999, i.e. the first 1,000 results. A URL ending "?page=1&size=1236" contains results 1,000 through 1,236.

Below is a script with a (lightly tested) modification of descendants() that I've made work with our query (also included): if the result list length is greater than 1000, it produces multiple URLs and loops through them, concatenating the results. I imagine other functions using these URL queries may have similar issues, though, so you may have a different solution you'd rather enact en masse.

```
library(rols)
library(httr)

descendants2 <- function(id){
  pagesize <- 20
  stopifnot(inherits(id, "Term"))
  url0 <- id@links$descendants[[1]]
  if (is.null(url0)) {
    message("No descendant terms.")
    return(NULL)
  }
  url <- paste0(url0, "?page=0&size=", pagesize)
  x <- httr::GET(url)
  stop_for_status(x)
  cx <- content(x)
  if(cx$page$totalElements > pagesize){
    pagesize <- cx$page$totalElements
    
    #Figure out how many URLs the results will divide into.
    url_pages <- c(0:(ceiling(pagesize/1000)-1))
    
    #Make as many URLs as there are pages anticipated.
    url <- paste0(url0, "?page=",url_pages,"&size=", pagesize)
    
    #Loop through queries of each URL.
    cx  <- lapply(url, function(x) {
      a <- GET(x)
      warn_for_status(a)
      a <- content(a)})
  }else{
    #Put singular <cx> into a list for lapply()'s sake.
    cx  <- list(cx)
  }
  ans   <- lapply(cx, function(x)
            lapply(x[["_embedded"]][[1]], rols:::makeTerm))
  #Concatenate all <cx> results into one list.
  ans   <- do.call(c,ans)
  
  names(ans) <- sapply(ans, termId)
  rols:::Terms(x = ans)
}


ont <- Ontology("efo")
trm	<- term(ont, "EFO:0000311")
(desd 	<- descendants(trm) ) 	# This should have 1,236 results.
(desd2 	<- descendants2(trm))
```

**Comment by hendrikweisser** [comment]
I encountered the same problem as @AndrewC160. I can confirm that his modified function works. (Thanks for providing it!)
I second the request for updating the package accordingly.

**Comment by lgatto** [comment]
Apologies for my late reply. Thank you @AndrewC160 for identifying the issue and providing a solution. Would you be able to submit a pull request replacing the `descendants()` implementation with yours? If not, I am happy to do it myself. If you do, please also add yourself as a contributor in the DESCRIPTION file.

**Comment by AndrewC160** [comment]
Will do, glad to help!
