### ISSUE TITLE
Why not add as.data.frame.OlsSearch?

### ISSUE THREAD

**Issue by LTLA** [lgatto/rols#31]
The vignette suggests using `as(qry, "data.frame")`, but adding `as.data.frame(qry)` would be helpful; less typing, and a more expected method for coercing objects to a `data.frame`.

**Comment by lgatto** [comment]
It's a matter of taste. PR welcome though.

**Comment by LTLA** [comment]
Most Vector subclasses already support `as.data.frame`, e.g., `DFrame`, `GRanges`. There can only be benefit in adding a similar method for your objects, it should be as simple as:

```r
#' @method as.data.frame OlsSearch
as.data.frame.OlsSearch <- function(x) {
    as(x, "data.frame")
}
```

This should improve the consistency of your interface with the rest of the BioC ecosystem.
