### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ssun1116** [lgatto/rols#37]
Hello,

I would like to inform you that it's currently unable to install the "rols" package using the method mentioned in the readme file (`BiocManager::install("rols")`).
Instead, I have found that the package can only be installed through the command `remotes::install_github("lgatto/rols")`.

Could you please check on this issue? 

Thank you,
Seoyeon

**Comment by lgatto** [comment]
A couple of comments:
- These two installation approaches will (or might, depending on the system) lead to different versions being installed. 
- Using `BiocManager::install("rols")` is the official/preferred way to install the package.
- What error was produced with `BiocManager::install("rols")`. I can't reproduce locally.
