### ISSUE TITLE
Documentation URL needs to be updated

### ISSUE THREAD

**Issue by ramiromagno** [lgatto/rols#38]
https://github.com/lgatto/rols/blob/3a4decca13b5b58c221d09f3fe6d0be5d4fae63e/DESCRIPTION#L24C6-L24C36

**Comment by lgatto** [comment]
Why so?

**Comment by ramiromagno** [comment]
Because it gives a  404.

**Comment by ramiromagno** [comment]
https://lgatto.github.io/rols/ works though.

**Comment by lgatto** [comment]
How have I missed this - thanks !
