### ISSUE TITLE
Add hierarchicalAncestors/Descendants

### ISSUE THREAD

**Issue by quirinmanz** [lgatto/rols#43]
Hi, 
It would be great to have a function to access the hierarchical ancestors and descendants, as they already have endpoints in the OLS API.
Best,
Quirin

**Comment by lgatto** [comment]
Yes, indeed, that's for later - the priority was to move to OLS4. Once all rough edges have been addressed, I'll do that.

**Comment by lgatto** [comment]
They are available  - see `?ancestors`.
